import SP1Clean.Core
import SP1Clean.Alignment.Chips.AddChip.Bridge
import SP1Clean.Alignment.Chips.AddChip.Contracts
import SP1Clean.Alignment.Chips.AddiChip.Bridge
import SP1Clean.Alignment.Chips.AddiChip.Contracts
import SP1Clean.Alignment.Chips.AddwChip.Bridge
import SP1Clean.Alignment.Chips.AddwChip.Contracts
import SP1Clean.Alignment.Chips.AluX0Chip.Bridge
import SP1Clean.Alignment.Chips.BitwiseChip.Bridge
import SP1Clean.Alignment.Chips.BitwiseChip.Contracts
import SP1Clean.Alignment.Chips.BranchChip.Bridge
import SP1Clean.Alignment.Chips.DecodedProgramProvider.Bridge
import SP1Clean.Alignment.Chips.DivRemChip.Bridge
import SP1Clean.Alignment.Chips.DivRemChip.Contracts
import SP1Clean.Alignment.Chips.JalChip.Bridge
import SP1Clean.Alignment.Chips.JalrChip.Bridge
import SP1Clean.Alignment.Chips.LoadByteChip.Bridge
import SP1Clean.Alignment.Chips.LoadByteChip.Contracts
import SP1Clean.Alignment.Chips.LoadDoubleChip.Bridge
import SP1Clean.Alignment.Chips.LoadDoubleChip.Contracts
import SP1Clean.Alignment.Chips.LoadHalfChip.Bridge
import SP1Clean.Alignment.Chips.LoadHalfChip.Contracts
import SP1Clean.Alignment.Chips.LoadWordChip.Bridge
import SP1Clean.Alignment.Chips.LoadWordChip.Contracts
import SP1Clean.Alignment.Chips.LoadX0Chip.Bridge
import SP1Clean.Alignment.Chips.LoadX0Chip.Contracts
import SP1Clean.Alignment.Chips.LtChip.Bridge
import SP1Clean.Alignment.Chips.LtChip.Contracts
import SP1Clean.Alignment.Chips.MulChip.Bridge
import SP1Clean.Alignment.Chips.MulChip.Contracts
import SP1Clean.Alignment.Chips.ShiftLeftChip.Bridge
import SP1Clean.Alignment.Chips.ShiftLeftChip.Contracts
import SP1Clean.Alignment.Chips.ShiftRightChip.Bridge
import SP1Clean.Alignment.Chips.ShiftRightChip.Contracts
import SP1Clean.Alignment.Chips.StoreByteChip.Bridge
import SP1Clean.Alignment.Chips.StoreDoubleChip.Bridge
import SP1Clean.Alignment.Chips.StoreHalfChip.Bridge
import SP1Clean.Alignment.Chips.StoreWordChip.Bridge
import SP1Clean.Alignment.Chips.SubChip.Bridge
import SP1Clean.Alignment.Chips.SubChip.Contracts
import SP1Clean.Alignment.Chips.SubwChip.Bridge
import SP1Clean.Alignment.Chips.SubwChip.Contracts
import SP1Clean.Alignment.Chips.UTypeChip.Bridge
import SP1Clean.Composition.Balance
import SP1Clean.Composition.Chips
import SP1Clean.Composition.CoreArtifact
import SP1Clean.Composition.CoreEnsemble
import SP1Clean.Composition.CoreSystemSemantics
import SP1Clean.Composition.Ensemble
import SP1Clean.Composition.Extracted
import SP1Clean.Composition.MemoryBoundary
import SP1Clean.Composition.PreprocessedProviders
import SP1Clean.Composition.ProviderSegment
import SP1Clean.Composition.SystemTables
import SP1Clean.Composition.Table
import SP1Clean.Extracted.ALUTypeReader
import SP1Clean.Extracted.AddOperation
import SP1Clean.Extracted.AddrAddOperation
import SP1Clean.Extracted.AddressOperation
import SP1Clean.Extracted.CPUState
import SP1Clean.Extracted.ChipOracle.Add
import SP1Clean.Extracted.ChipOracle.Addi
import SP1Clean.Extracted.ChipOracle.Addw
import SP1Clean.Extracted.ChipOracle.AluX0
import SP1Clean.Extracted.ChipOracle.Bitwise
import SP1Clean.Extracted.ChipOracle.Branch
import SP1Clean.Extracted.ChipOracle.DivRem
import SP1Clean.Extracted.ChipOracle.Jal
import SP1Clean.Extracted.ChipOracle.Jalr
import SP1Clean.Extracted.ChipOracle.LoadByte
import SP1Clean.Extracted.ChipOracle.LoadDouble
import SP1Clean.Extracted.ChipOracle.LoadHalf
import SP1Clean.Extracted.ChipOracle.LoadWord
import SP1Clean.Extracted.ChipOracle.LoadX0
import SP1Clean.Extracted.ChipOracle.Lt
import SP1Clean.Extracted.ChipOracle.Mul
import SP1Clean.Extracted.ChipOracle.ShiftLeft
import SP1Clean.Extracted.ChipOracle.ShiftRight
import SP1Clean.Extracted.ChipOracle.StoreByte
import SP1Clean.Extracted.ChipOracle.StoreDouble
import SP1Clean.Extracted.ChipOracle.StoreHalf
import SP1Clean.Extracted.ChipOracle.StoreWord
import SP1Clean.Extracted.ChipOracle.Sub
import SP1Clean.Extracted.ChipOracle.Subw
import SP1Clean.Extracted.ChipOracle.UType
import SP1Clean.Extracted.CoreAIRManifest
import SP1Clean.Extracted.ExtractionDSL
import SP1Clean.Extracted.ITypeReader
import SP1Clean.Extracted.ITypeReaderImmutable
import SP1Clean.Extracted.InteractionModel
import SP1Clean.Extracted.IsEqualWordOperation
import SP1Clean.Extracted.IsZeroOperation
import SP1Clean.Extracted.IsZeroWordOperation
import SP1Clean.Extracted.JTypeReader
import SP1Clean.Extracted.LtOperationSigned
import SP1Clean.Extracted.LtOperationUnsigned
import SP1Clean.Extracted.MemoryAccess
import SP1Clean.Extracted.MulOperation
import SP1Clean.Extracted.OpcodeTable
import SP1Clean.Extracted.Provenance
import SP1Clean.Extracted.RTypeReader
import SP1Clean.Extracted.SystemOracle.Byte
import SP1Clean.Extracted.SystemOracle.Global
import SP1Clean.Extracted.SystemOracle.MemoryBump
import SP1Clean.Extracted.SystemOracle.MemoryGlobalFinalize
import SP1Clean.Extracted.SystemOracle.MemoryGlobalInit
import SP1Clean.Extracted.SystemOracle.MemoryLocal
import SP1Clean.Extracted.SystemOracle.Program
import SP1Clean.Extracted.SystemOracle.PublicValues
import SP1Clean.Extracted.SystemOracle.Range
import SP1Clean.Extracted.SystemOracle.StateBump
import SP1Clean.Extracted.SystemOracle.SyscallCore
import SP1Clean.Extracted.SystemOracle.SyscallInstrs
import SP1Clean.Extracted.U16CompareOperation
import SP1Clean.Extracted.U16MSBOperation
import SP1Clean.Extracted.U16toU8OperationSafe
import SP1Clean.Extracted.U16toU8OperationUnsafe
import SP1Clean.Faithful.ALUTypeReader
import SP1Clean.Faithful.AddChip
import SP1Clean.Faithful.AddOperation
import SP1Clean.Faithful.AddiChip
import SP1Clean.Faithful.AddwChip
import SP1Clean.Faithful.AluX0Chip
import SP1Clean.Faithful.BitwiseChip
import SP1Clean.Faithful.BranchChip
import SP1Clean.Faithful.CPUState
import SP1Clean.Faithful.ChipOracle
import SP1Clean.Faithful.ChipTactics
import SP1Clean.Faithful.CoreAIR
import SP1Clean.Faithful.DivRemChip
import SP1Clean.Faithful.DivRemChip.Exact
import SP1Clean.Faithful.ITypeReaderImmutable
import SP1Clean.Faithful.IsEqualWordOperation
import SP1Clean.Faithful.IsZeroOperation
import SP1Clean.Faithful.IsZeroWordOperation
import SP1Clean.Faithful.JalChip
import SP1Clean.Faithful.JalrChip
import SP1Clean.Faithful.LoadByteChip
import SP1Clean.Faithful.LoadDoubleChip
import SP1Clean.Faithful.LoadHalfChip
import SP1Clean.Faithful.LoadWordChip
import SP1Clean.Faithful.LoadX0Chip
import SP1Clean.Faithful.LtChip
import SP1Clean.Faithful.LtOperationUnsigned
import SP1Clean.Faithful.MemoryBumpChip
import SP1Clean.Faithful.MulChip
import SP1Clean.Faithful.RTypeReader
import SP1Clean.Faithful.ShiftLeftChip
import SP1Clean.Faithful.ShiftRightChip
import SP1Clean.Faithful.StateBumpChip
import SP1Clean.Faithful.StoreByteChip
import SP1Clean.Faithful.StoreDoubleChip
import SP1Clean.Faithful.StoreHalfChip
import SP1Clean.Faithful.StoreWordChip
import SP1Clean.Faithful.SubChip
import SP1Clean.Faithful.SubwChip
import SP1Clean.Faithful.SupportedMachine
import SP1Clean.Faithful.SyscallInstrsChip
import SP1Clean.Faithful.SyscallRowDecode
import SP1Clean.Faithful.U16CompareOperation
import SP1Clean.Faithful.U16MSBOperation
import SP1Clean.Faithful.U16toU8OperationSafe
import SP1Clean.Faithful.UTypeChip
import SP1Clean.Proofs.Completeness.AluGeneration
import SP1Clean.Proofs.Completeness.Assembly
import SP1Clean.Proofs.Completeness.CanonicalClosure
import SP1Clean.Proofs.Completeness.CanonicalClosureWellFormed
import SP1Clean.Proofs.Completeness.ChipLedger
import SP1Clean.Proofs.Completeness.Closure
import SP1Clean.Proofs.Completeness.ClosureRealization
import SP1Clean.Proofs.Completeness.ConsumerClosure
import SP1Clean.Proofs.Completeness.EventBuckets
import SP1Clean.Proofs.Completeness.ExecutionCompiler
import SP1Clean.Proofs.Completeness.FieldClosure
import SP1Clean.Proofs.Completeness.Footprint
import SP1Clean.Proofs.Completeness.InstructionEvent
import SP1Clean.Proofs.Completeness.Ledger
import SP1Clean.Proofs.Completeness.MemoryHistory
import SP1Clean.Proofs.Completeness.NativeBoundaryAgreement
import SP1Clean.Proofs.Completeness.NativeMemoryAgreement
import SP1Clean.Proofs.Completeness.NativeProgramAgreement
import SP1Clean.Proofs.Completeness.NativeStateAgreement
import SP1Clean.Proofs.Completeness.NativeTraceCompiler
import SP1Clean.Proofs.Completeness.ProviderInteractions
import SP1Clean.Proofs.Completeness.ProviderTables
import SP1Clean.Proofs.Completeness.ProviderWitgen
import SP1Clean.Proofs.Completeness.Providers
import SP1Clean.Proofs.Completeness.StateHistory
import SP1Clean.Proofs.Sail.Advance
import SP1Clean.Proofs.Sail.InstructionDecode
import SP1Clean.Proofs.Sail.InstructionDecode.Families
import SP1Clean.Proofs.Sail.InstructionDecode.Tactic
import SP1Clean.Proofs.Sail.RV64Bridge
import SP1Clean.Proofs.Sail.TryStepReduction
import SP1Clean.Soundness.AIR
import SP1Clean.Soundness.AIRCompleteness
import SP1Clean.Soundness.AlignedCarrier
import SP1Clean.Soundness.BootHalt
import SP1Clean.Soundness.BumpDecode
import SP1Clean.Soundness.ChipContracts
import SP1Clean.Soundness.ChipRegistry
import SP1Clean.Soundness.ChipRow
import SP1Clean.Soundness.CoreAIR
import SP1Clean.Soundness.CoreAIRSyscallFree
import SP1Clean.Soundness.CoreExecutionEvents
import SP1Clean.Soundness.CoreExecutionRow
import SP1Clean.Soundness.CoreExecutionTrajectory
import SP1Clean.Soundness.CoreHaltExecution
import SP1Clean.Soundness.CoreInstructionExecution
import SP1Clean.Soundness.CoreMemoryBalance
import SP1Clean.Soundness.CoreMemoryChronology
import SP1Clean.Soundness.CoreMemoryFrame
import SP1Clean.Soundness.CoreProgramBalance
import SP1Clean.Soundness.CoreRowBalance
import SP1Clean.Soundness.CoreRowTransport
import SP1Clean.Soundness.CoreTableProjection
import SP1Clean.Soundness.CoreTouches
import SP1Clean.Soundness.Coverage
import SP1Clean.Soundness.Decode
import SP1Clean.Soundness.EnsembleChannels
import SP1Clean.Soundness.ExitAccounting
import SP1Clean.Soundness.FetchDiscriminant
import SP1Clean.Soundness.FinalMemoryEnsemble
import SP1Clean.Soundness.FinishedChannels
import SP1Clean.Soundness.GenericWalk
import SP1Clean.Soundness.GoodnessFilter
import SP1Clean.Soundness.Grounding.ALUTypeChips
import SP1Clean.Soundness.Grounding.ControlFlowChips
import SP1Clean.Soundness.Grounding.ITypeChips
import SP1Clean.Soundness.Grounding.JTypeChips
import SP1Clean.Soundness.Grounding.MemoryCell
import SP1Clean.Soundness.Grounding.MemoryChips
import SP1Clean.Soundness.Grounding.RTypeChips
import SP1Clean.Soundness.GroundingAdapter
import SP1Clean.Soundness.GroundingInternal
import SP1Clean.Soundness.HaltExecution
import SP1Clean.Soundness.HaltGrounding
import SP1Clean.Soundness.HaltPadding
import SP1Clean.Soundness.HintQueueHistory
import SP1Clean.Soundness.HintReadCoverage
import SP1Clean.Soundness.HintReadWriteLedger
import SP1Clean.Soundness.HintReadWrites
import SP1Clean.Soundness.HostBankCPUReplay
import SP1Clean.Soundness.HostCallLedger
import SP1Clean.Soundness.HostCallOrder
import SP1Clean.Soundness.HostCallProjection
import SP1Clean.Soundness.HostCallReceivers
import SP1Clean.Soundness.HostCommitBank
import SP1Clean.Soundness.HostCommitEnsemble
import SP1Clean.Soundness.HostCommitHistory
import SP1Clean.Soundness.HostExecutionEffect
import SP1Clean.Soundness.HostFootprint
import SP1Clean.Soundness.HostHintQueueBoundary
import SP1Clean.Soundness.HostHintQueueHistory
import SP1Clean.Soundness.HostHintReadBankAgreement
import SP1Clean.Soundness.HostHintReadBanks
import SP1Clean.Soundness.HostHintReadBookkeeping
import SP1Clean.Soundness.HostHintReadCPUMemory
import SP1Clean.Soundness.HostHintReadCoverage
import SP1Clean.Soundness.HostHintReadExecution
import SP1Clean.Soundness.HostHintReadExecutionPath
import SP1Clean.Soundness.HostHintReadExecutionRows
import SP1Clean.Soundness.HostHintReadExit
import SP1Clean.Soundness.HostHintReadFinalMemory
import SP1Clean.Soundness.HostHintReadFinalSnapshot
import SP1Clean.Soundness.HostHintReadGrounding
import SP1Clean.Soundness.HostHintReadHandoff
import SP1Clean.Soundness.HostHintReadHostAgreement
import SP1Clean.Soundness.HostHintReadInstructionExecution
import SP1Clean.Soundness.HostHintReadLocal
import SP1Clean.Soundness.HostHintReadLocalExecution
import SP1Clean.Soundness.HostHintReadLocalMemory
import SP1Clean.Soundness.HostHintReadLocalPermissions
import SP1Clean.Soundness.HostHintReadLocalQueue
import SP1Clean.Soundness.HostHintReadLocalRecords
import SP1Clean.Soundness.HostHintReadMemoryEffect
import SP1Clean.Soundness.HostHintReadMemoryOrder
import SP1Clean.Soundness.HostHintReadPartition
import SP1Clean.Soundness.HostHintReadSyscallExecution
import SP1Clean.Soundness.HostHintReadTerminalAgreement
import SP1Clean.Soundness.HostHintReadTerminalProjection
import SP1Clean.Soundness.HostHintReadTrajectory
import SP1Clean.Soundness.HostHintReadWrites
import SP1Clean.Soundness.HostHintRecordSources
import SP1Clean.Soundness.HostLocalCore
import SP1Clean.Soundness.HostLocalCoreAuthentication
import SP1Clean.Soundness.HostLocalCoreLedger
import SP1Clean.Soundness.HostLocalCoreMemory
import SP1Clean.Soundness.HostLocalCoreMemoryBounds
import SP1Clean.Soundness.HostLocalCorePermissions
import SP1Clean.Soundness.HostLocalCoreProgram
import SP1Clean.Soundness.HostLocalCoreRom
import SP1Clean.Soundness.HostLocalCoreRows
import SP1Clean.Soundness.HostLocalHandoff
import SP1Clean.Soundness.HostQueueCPUOrder
import SP1Clean.Soundness.HostQueueCPUReplay
import SP1Clean.Soundness.HostQueueCallProjection
import SP1Clean.Soundness.HostQueueCurrent
import SP1Clean.Soundness.HostQueueHistory
import SP1Clean.Soundness.HostQueueOrder
import SP1Clean.Soundness.HostRamTouches
import SP1Clean.Soundness.HostTerminalLedger
import SP1Clean.Soundness.InitialMemoryBoundary
import SP1Clean.Soundness.InitialMemoryEnsemble
import SP1Clean.Soundness.LocalCoreBoundaries
import SP1Clean.Soundness.LocalCoreChannels
import SP1Clean.Soundness.LocalCoreDecode
import SP1Clean.Soundness.LocalCoreEnsemble
import SP1Clean.Soundness.LocalCoreEventUniqueness
import SP1Clean.Soundness.LocalCoreExit
import SP1Clean.Soundness.LocalCoreFinalBoundary
import SP1Clean.Soundness.LocalCoreGrounding
import SP1Clean.Soundness.LocalCoreHaltExecution
import SP1Clean.Soundness.LocalCoreInstructionExecution
import SP1Clean.Soundness.LocalCoreMemory
import SP1Clean.Soundness.LocalCoreMemoryOrder
import SP1Clean.Soundness.LocalCoreOrder
import SP1Clean.Soundness.LocalCoreProgram
import SP1Clean.Soundness.LocalCoreRowBalance
import SP1Clean.Soundness.LocalCoreRows
import SP1Clean.Soundness.LocalCoreSourceGrounding
import SP1Clean.Soundness.LocalCoreState
import SP1Clean.Soundness.LocalCoreTouches
import SP1Clean.Soundness.LocalCoreTrajectory
import SP1Clean.Soundness.LocalCoreTransport
import SP1Clean.Soundness.LocalExecution
import SP1Clean.Soundness.MemoryBoundaryTruth
import SP1Clean.Soundness.MemoryFrontier
import SP1Clean.Soundness.MixedRowTransport
import SP1Clean.Soundness.NativeCompleteness
import SP1Clean.Soundness.NativeCoreBoundaries
import SP1Clean.Soundness.NativeCoreDecode
import SP1Clean.Soundness.NativeCoreEnsemble
import SP1Clean.Soundness.NativeCoreFinalBoundary
import SP1Clean.Soundness.NativeCoreGrounding
import SP1Clean.Soundness.NativeCoreHaltExecution
import SP1Clean.Soundness.NativeCoreInstructionExecution
import SP1Clean.Soundness.NativeCoreMemory
import SP1Clean.Soundness.NativeCoreMemoryOrder
import SP1Clean.Soundness.NativeCoreOrder
import SP1Clean.Soundness.NativeCoreProgram
import SP1Clean.Soundness.NativeCoreRowBalance
import SP1Clean.Soundness.NativeCoreRows
import SP1Clean.Soundness.NativeCoreState
import SP1Clean.Soundness.NativeCoreSyscallSemantics
import SP1Clean.Soundness.NativeCoreTouches
import SP1Clean.Soundness.NativeCoreTrajectory
import SP1Clean.Soundness.NativeCoreTransport
import SP1Clean.Soundness.OrderedBoundaryEnsemble
import SP1Clean.Soundness.OrderedMemoryEnsemble
import SP1Clean.Soundness.ProtectedLocalCore
import SP1Clean.Soundness.ProtectedLocalCoreExecution
import SP1Clean.Soundness.ProtectedLocalCorePermissions
import SP1Clean.Soundness.ProtectedLocalCoreProjection
import SP1Clean.Soundness.ProtectedLocalCoreRom
import SP1Clean.Soundness.ProtectedStoreFootprints
import SP1Clean.Soundness.ProtectedStorePermissions
import SP1Clean.Soundness.ProviderBindings
import SP1Clean.Soundness.RankedGrounding
import SP1Clean.Soundness.RefreshElimination
import SP1Clean.Soundness.RefreshWiring
import SP1Clean.Soundness.RomWriteProtection
import SP1Clean.Soundness.RowEffectDefs
import SP1Clean.Soundness.RowSoundness
import SP1Clean.Soundness.SP1Ensemble
import SP1Clean.Soundness.Shard.Contract
import SP1Clean.Soundness.Shard.Machine
import SP1Clean.Soundness.SnapshotMemoryEnsemble
import SP1Clean.Soundness.StateCanon
import SP1Clean.Soundness.StateChronology
import SP1Clean.Soundness.StatePcClass
import SP1Clean.Soundness.SupportedMachine
import SP1Clean.Soundness.SyscallExecution
import SP1Clean.Soundness.SyscallGrounding
import SP1Clean.Soundness.SyscallInputs
import SP1Clean.Soundness.SyscallRowSemantics
import SP1Clean.Soundness.SyscallTrail
import SP1Clean.Soundness.SyscallWiring
import SP1Clean.Soundness.SystemMemoryRows
import SP1Clean.Soundness.SystemStateRows
import SP1Clean.Soundness.SystemTouches
import SP1Clean.Soundness.TimeExtraction
import SP1Clean.Soundness.TimedGrounding
import SP1Clean.Soundness.TouchChains
import SP1Clean.Soundness.TypedInteractions
import SP1Clean.Soundness.TypedMemory
import SP1Clean.Soundness.TypedMemoryBalance
import SP1Clean.Soundness.TypedMemorySelectors
import SP1Clean.Soundness.TypedProgram
import SP1Clean.Soundness.TypedSelectors
import SP1Clean.Soundness.TypedState
import SP1Clean.Soundness.TypedTime
import SP1Clean.Soundness.TypedTimeContracts
import SP1Clean.Soundness.Walk
import SP1Clean.Soundness.WalkTimeline
import SP1Clean.Soundness.WitnessDecode
import SP1Clean.Soundness.WritePermissionBalance
import ToClean.Air.CompleteEnsemble
import ToClean.Air.EnsembleExport

/-! # The umbrella index

Root of the `SP1Clean` library: the core (`SP1Clean.Core`, strata 0–6) plus the SP1-alignment
strata 7–11 (`Faithful`, `Alignment`, `Proofs/Sail`, `Proofs/Completeness`, `Soundness`,
`Composition`) and every generated `Extracted/` module. `lake build SP1Clean` is the full build;
`scripts/check_root_index.sh` fails if a module on disk is missing from this closure. -/
