import SP1Clean.Extracted.ExtractionDSL
import SP1Clean.Model.InteractionProjection
import SP1Clean.Model.ByteTable

/-! # Syntactic projection of the EXTRACTED interaction ADT to `LookupAccess`

**Hand-written** (not generated by `update_extracted.py`), and here rather than in `Faithful/` for
the reason `ExtractionDSL.lean` gives for itself: this is the extracted-oracle bus vocabulary, so it
belongs beside the `Interaction` type it projects. It lived under `Faithful/` until 2026-08 purely
because faithfulness was its first consumer — while declaring `namespace SP1Clean.Extracted` the
whole time. That mismatch is what put `toAccess` out of reach of the completeness layer, which
legitimately needs it; `scripts/check_layering.sh` now checks namespace against path so the same slip
fails the build instead of surfacing months later as an unexplained blocker.

The extracted-side counterpart of `AbstractInteraction.toAccess` (`Model/InteractionProjection.lean`).
The extracted `Interaction (ZMod p)` (the SP1-oracle bus vocabulary, `Extracted/ExtractionDSL.lean`)
projected to the **same** `LookupAccess` tuple `(kind, table, argvals, signedmult)` that the Clean
circuit's emitted interactions project to. Equality of the two `.map toAccess` lists is the *syntactic*
faithfulness bridge: it compares the channel, the message arg **values**, and the **signed
multiplicity/direction** — not byte semantics (unlike `Interaction.toProp`, which collapses every
non-byte interaction to `True` and reasons about `op.constrain`/`< 65536`).

## Sign convention (the one modeling gap the syntactic comparison surfaces)

Clean models the byte lookup as a **pull** — `byteChannel.pullIf is_real` → `pullIf`, with
multiplicity `-is_real` on `byteChannel.toRaw` (`Native/Operations/AddOperation/Defs.lean`). SP1's
`send_byte` is the dual **source** endpoint (`Extracted/AddOperation.lean`: `⟨.send, .byte 6 v 16 0,
is_real⟩`). Same physical lookup, opposite source/sink convention — so the `.byte` arm records the
**negated** direction sign `signedVal (-(dir.sign mult))`: the whole byte channel is sign-flipped
relative to the extracted vocabulary, uniformly for both directions (a chip's `.send` lands as the
native pull `-mult`; a provider table's `.receive` lands as the native push `+mult`). The message
tuple `[opcode.val, a.val, b.val, c.val]` preserves Rust's raw field-valued opcode. The dynamic
buses (State/Memory/Program) use the natural `Dir.sign` (`pushIf` send `+mult`, receive `-mult`) —
byte is the sole *pull* bus (`Model/Channels.lean` `byteChannel` docstring), hence its flip. (An
earlier revision hardcoded `-mult` ignoring the direction — correct for every chip interaction,
which only ever sends byte, but sign-wrong for the upstream Byte/Range provider tables' `.receive`s;
fixed 2026-08, external report F18.) -/

namespace SP1Clean.Extracted

open SP1Clean

variable {p : ℕ}

/-! ## Typed message adapters

The generated oracle remains authoritative for directions and multiplicities. These constructors
only turn the shared Model-layer message carriers into the exact extracted payload ADT, so semantic
adapters can name a bus tuple without copying its field list. -/

/-- Embed a typed Memory message into the exact nine-field Memory payload. -/
def AirInteraction.ofMemoryMsg {F : Type} (msg : Channels.MemoryMsg F) : AirInteraction F :=
  .memory msg.clk_high msg.clk_low msg.addr0 msg.addr1 msg.addr2
    msg.value[0] msg.value[1] msg.value[2] msg.value[3]

/-- Embed the shared typed Syscall message into the pinned raw Syscall payload. -/
def AirInteraction.ofSyscallMsg {F : Type} (msg : Channels.SyscallMsg F) : AirInteraction F :=
  .raw .syscall (toElements msg).toList

/-- The signed multiplicity of an extracted interaction by direction. Local and global sends are
positive; local and global receives are negative, matching the upstream interaction polarity. -/
def Dir.sign (d : Dir) (mult : ZMod p) : ZMod p :=
  match d with
  | .send | .sendGlobal => mult
  | .receive | .receiveGlobal => -mult

/-- Stable names for the exact upstream bus discriminator when it passes through the older
four-bus `LookupAccess` compatibility projection. The full Core relation does not use this
encoding: it compares `AirInteractionKind` and `AirInteraction.raw` directly. -/
def AirInteractionKind.lookupName : AirInteractionKind → String
  | .memory => "memory"
  | .program => "program"
  | .byte => "byte"
  | .state => "state"
  | .syscall => "syscall"
  | .global => "global"
  | .shaExtend => "sha-extend"
  | .shaCompress => "sha-compress"
  | .keccak => "keccak"
  | .globalAccumulation => "global-accumulation"
  | .memoryGlobalInitControl => "memory-global-init-control"
  | .memoryGlobalFinalizeControl => "memory-global-finalize-control"
  | .instructionFetch => "instruction-fetch"
  | .instructionDecode => "instruction-decode"
  | .pageProt => "page-prot"
  | .pageProtAccess => "page-prot-access"
  | .pageProtGlobalInitControl => "page-prot-global-init-control"
  | .pageProtGlobalFinalizeControl => "page-prot-global-finalize-control"

/-- The `InteractionKind` a raw upstream bus projects to. `syscall` is a bus this project models,
so it gets its own kind; everything else is honestly `Unmodelled` (see `Model/InteractionBus.lean`).

Kept as a function on the discriminator rather than as a second `.raw` arm of
`Interaction.toAccess`'s match. Two `.raw` arms overlap, so the equation compiler emits one equation
whose body is a *nested* `casesOn` over all eighteen `AirInteractionKind` constructors, and every
interaction in a chip's list drags that behind it. The equation *count* is one either way —
`toAccess` matches on a projection, not a parameter — so `#print equations` does not show the
difference.

This is a modelling preference, not a fix for anything: the `SyscallInstrs` oracle-block
normalisation that motivated the investigation was slow for an unrelated reason (a monolithic `simp`
congruence term hitting the kernel size cliff, see `Faithful/SyscallInstrsChip.lean`), and stayed
slow after this change until that was addressed. -/
def AirInteractionKind.lookupKind : AirInteractionKind → InteractionKind
  | .syscall => .Syscall
  | _ => .Unmodelled

/-- The table name a raw upstream bus projects to: the syscall bus shares the native channel's
`"SP1Syscall"`, everything else keeps its exact discriminator in a reserved name. -/
def AirInteractionKind.lookupTable (k : AirInteractionKind) : String :=
  match k with
  | .syscall => "SP1Syscall"
  | _ => "SP1Raw/" ++ k.lookupName

@[simp] theorem AirInteractionKind.lookupKind_syscall :
    AirInteractionKind.lookupKind .syscall = InteractionKind.Syscall := rfl

@[simp] theorem AirInteractionKind.lookupTable_syscall :
    AirInteractionKind.lookupTable .syscall = "SP1Syscall" := rfl

/-- Project one extracted interaction to its legacy `LookupAccess` compatibility representation.
The `.byte` arm negates the direction sign (`signedVal (-(dir.sign mult))` — Clean's pull-bus
convention, applied uniformly to sends and receives); the dynamic buses use the plain `Dir.sign`.

The `.raw` arm splits. SP1's **syscall** bus is a bus this project models, so it projects to
`InteractionKind.Syscall` under the same `"SP1Syscall"` name the native `Channels.syscallChannel`
carries — that agreement on *both* components of the key is what lets a whole-chip anchor compare a
syscall send to a syscall send. Every other raw bus (`global`, `globalAccumulation`, the two
`MemoryGlobal*Control`, the two `PageProtGlobal*Control`, the precompile buses) is not modelled
here, and says so: `InteractionKind.Unmodelled`, keeping its exact discriminator in a reserved
`"SP1Raw/<kind>"` name so distinct buses stay distinct keys. Neither is a compatibility alias onto a
bus that *is* modelled. `CoreAIR.Current.Balance.Valid` compares the exact raw payload ADT and never
passes through this encoding. -/
def Interaction.toAccess (intr : Interaction (ZMod p)) : LookupAccess :=
  match intr.payload with
  | .byte opcode a b c =>
      (InteractionKind.Byte, "SP1Byte",
        [opcode.val, a.val, b.val, c.val], signedVal (- intr.dir.sign intr.mult))
  | .state a b c d e =>
      (InteractionKind.State, "SP1State",
        [a.val, b.val, c.val, d.val, e.val], signedVal (intr.dir.sign intr.mult))
  | .memory a b c d e f g h i =>
      (InteractionKind.Memory, "SP1Memory",
        [a.val, b.val, c.val, d.val, e.val, f.val, g.val, h.val, i.val],
        signedVal (intr.dir.sign intr.mult))
  | .program a b c op d e f g h i j k l m n o =>
      (InteractionKind.Program, "SP1Program",
        [a.val, b.val, c.val, op, d.val, e.val, f.val, g.val, h.val,
         i.val, j.val, k.val, l.val, m.val, n.val, o.val],
        signedVal (intr.dir.sign intr.mult))
  | .raw kind values =>
      (kind.lookupKind, kind.lookupTable, values.map ZMod.val,
        signedVal (intr.dir.sign intr.mult))

/-- The `.byte` arm of `Interaction.toAccess` at a `.send` — the form every chip interaction takes
(chips only ever send byte), recording the native pull sign `-mult`. Drives the syntactic
faithfulness proofs. The dual `.receive` form is `Interaction.toAccess_byte_receive`. -/
@[simp] lemma Interaction.toAccess_byte (opcode a b c mult : ZMod p) :
    (⟨.send, .byte opcode a b c, mult⟩ : Interaction (ZMod p)).toAccess
      = (InteractionKind.Byte, "SP1Byte",
        [opcode.val, a.val, b.val, c.val], signedVal (-mult)) :=
  rfl

/-- The `.byte` arm of `Interaction.toAccess` at a `.receive` — the provider-table form (the
upstream Byte/Range tables receive the lookups), recording the native push sign `+mult`. -/
@[simp] lemma Interaction.toAccess_byte_receive (opcode a b c mult : ZMod p) :
    (⟨.receive, .byte opcode a b c, mult⟩ : Interaction (ZMod p)).toAccess
      = (InteractionKind.Byte, "SP1Byte",
        [opcode.val, a.val, b.val, c.val], signedVal mult) :=
  congrArg
    (fun m => (InteractionKind.Byte, "SP1Byte", [opcode.val, a.val, b.val, c.val], signedVal m))
    (neg_neg mult)

/-- Whether an extracted interaction carries the arity-preserving raw payload. The four typed
payloads project to the four SP1 instruction buses; only `.raw` reaches `Syscall` or `Unmodelled`,
so this is the single side condition an instruction chip's anchor has to discharge. -/
def Interaction.IsRaw (intr : Interaction (ZMod p)) : Prop :=
  ∃ kind values, intr.payload = .raw kind values

/-- No extracted interaction projects to either native-only kind. SP1's oracle vocabulary has no
exit bus and no public-values bus — it binds `exit_code` and the commit digests by direct
chip-level public-values access, which is exactly the access Clean's flat AIR reserves to the
verifier row and the native ensemble therefore routes over channels of its own. -/
theorem Interaction.toAccess_kind_not_native (intr : Interaction (ZMod p)) :
    (Interaction.toAccess intr).1 ≠ InteractionKind.Exit ∧
      (Interaction.toAccess intr).1 ≠ InteractionKind.PublicValues := by
  rcases intr with ⟨dir, payload, mult⟩
  cases payload
  case raw kind _ =>
    cases kind <;> simp [Interaction.toAccess, AirInteractionKind.lookupKind]
  all_goals simp [Interaction.toAccess]

/-- Retained under its historical name for `docs/release-audit.md`'s citation of the Exit half. -/
theorem Interaction.toAccess_kind_ne_exit (intr : Interaction (ZMod p)) :
    (Interaction.toAccess intr).1 ≠ InteractionKind.Exit :=
  (Interaction.toAccess_kind_not_native intr).1

/-- A typed payload projects to one of the four SP1 instruction buses — never to the syscall bus
and never to the unmodelled remainder. Both of those are reachable only through `.raw`. -/
theorem Interaction.toAccess_kind_not_raw (intr : Interaction (ZMod p)) (h : ¬ intr.IsRaw) :
    (Interaction.toAccess intr).1 ≠ InteractionKind.Syscall ∧
      (Interaction.toAccess intr).1 ≠ InteractionKind.Unmodelled := by
  rcases intr with ⟨dir, payload, mult⟩
  cases payload
  case raw kind values => exact absurd ⟨kind, values, rfl⟩ h
  all_goals simp [Interaction.toAccess]

/-- The four kinds an extracted oracle list cannot carry, given that it emits no raw interaction —
which is the case for every one of the twenty-five instruction chips. -/
theorem map_toAccess_filters_nil {l : List (Interaction (ZMod p))}
    (hraw : ∀ i ∈ l, ¬ i.IsRaw) (K : InteractionKind)
    (hK : K = .Exit ∨ K = .PublicValues ∨ K = .Syscall ∨ K = .Unmodelled) :
    (l.map Interaction.toAccess).filter (fun a => a.1 = K) = [] := by
  rw [List.filter_eq_nil_iff]
  intro a ha
  obtain ⟨i, hi, rfl⟩ := List.mem_map.mp ha
  obtain ⟨hexit, hpv⟩ := Interaction.toAccess_kind_not_native i
  obtain ⟨hsyscall, hother⟩ := Interaction.toAccess_kind_not_raw i (hraw i hi)
  rcases hK with rfl | rfl | rfl | rfl <;> simpa using ‹_›

/-! ## The four-block partition, for a table that touches only SP1's instruction buses

Every one of the twenty-five instruction chips emits typed payloads exclusively — not one
`Extracted/ChipOracle/*.lean` contains a `.raw` interaction — so its oracle's access list carries
none of the four kinds outside the State/Byte/Memory/Program group. That single fact is what these
two lemmas turn into the partition the whole-chip anchors assemble through, and the `IsRaw`
hypothesis is what stops a table that *does* touch the syscall bus (`SyscallInstrs`) or a global
bus (`Global`, `MemoryLocal`, the `MemoryGlobal*` pair) from being assembled the same way by
accident. -/

/-- The four-block kind partition of an extracted oracle's access list, for a table that emits no
raw interaction. -/
theorem perm_filter_by_kind_of_no_raw (l : List (Interaction (ZMod p)))
    (hraw : ∀ i ∈ l, ¬ i.IsRaw) :
    (l.map Interaction.toAccess).Perm
      ((l.map Interaction.toAccess).filter (fun a => a.1 = InteractionKind.State) ++
        (l.map Interaction.toAccess).filter (fun a => a.1 = InteractionKind.Byte) ++
        (l.map Interaction.toAccess).filter (fun a => a.1 = InteractionKind.Memory) ++
        (l.map Interaction.toAccess).filter (fun a => a.1 = InteractionKind.Program)) :=
  LookupAccessList.perm_filter_by_kind_of_sp1_only _
    (map_toAccess_filters_nil hraw _ (Or.inl rfl))
    (map_toAccess_filters_nil hraw _ (Or.inr (Or.inr (Or.inl rfl))))
    (map_toAccess_filters_nil hraw _ (Or.inr (Or.inl rfl)))
    (map_toAccess_filters_nil hraw _ (Or.inr (Or.inr (Or.inr rfl))))

/-- The same partition under the `active` restriction, for the two anchors that compare only
nonzero-multiplicity accesses. -/
theorem active_perm_filter_by_kind_of_no_raw (l : List (Interaction (ZMod p)))
    (hraw : ∀ i ∈ l, ¬ i.IsRaw) :
    (LookupAccessList.active (l.map Interaction.toAccess)).Perm
      ((LookupAccessList.active (l.map Interaction.toAccess)).filter
          (fun a => a.1 = InteractionKind.State) ++
        (LookupAccessList.active (l.map Interaction.toAccess)).filter
          (fun a => a.1 = InteractionKind.Byte) ++
        (LookupAccessList.active (l.map Interaction.toAccess)).filter
          (fun a => a.1 = InteractionKind.Memory) ++
        (LookupAccessList.active (l.map Interaction.toAccess)).filter
          (fun a => a.1 = InteractionKind.Program)) := by
  refine LookupAccessList.perm_filter_by_kind_of_sp1_only _ ?_ ?_ ?_ ?_ <;>
    (rw [List.filter_eq_nil_iff]
     intro a ha
     have hmem : a ∈ l.map Interaction.toAccess :=
       List.mem_of_mem_filter (l := l.map Interaction.toAccess)
         (p := fun access => decide (LookupAccessList.multOf access ≠ 0)) ha
     obtain ⟨i, hi, rfl⟩ := List.mem_map.mp hmem
     obtain ⟨hexit, hpv⟩ := Interaction.toAccess_kind_not_native i
     obtain ⟨hsyscall, hother⟩ := Interaction.toAccess_kind_not_raw i (hraw i hi)
     simpa using ‹_›)

/-- The Exit filter of any extracted access list is empty. -/
theorem map_toAccess_exit_filter (l : List (Interaction (ZMod p))) :
    (l.map Interaction.toAccess).filter
      (fun a => a.1 = InteractionKind.Exit) = [] := by
  rw [List.filter_eq_nil_iff]
  intro a ha
  obtain ⟨i, -, rfl⟩ := List.mem_map.mp ha
  simpa using Interaction.toAccess_kind_ne_exit i

/-- The Exit filter of an extracted access list survives the `active` restriction. -/
theorem active_map_toAccess_exit_filter (l : List (Interaction (ZMod p))) :
    (LookupAccessList.active (l.map Interaction.toAccess)).filter
      (fun a => a.1 = InteractionKind.Exit) = [] := by
  rw [List.filter_eq_nil_iff]
  intro a ha
  have hmem : a ∈ l.map Interaction.toAccess :=
    List.mem_of_mem_filter (l := l.map Interaction.toAccess)
      (p := fun access => decide (LookupAccessList.multOf access ≠ 0)) ha
  obtain ⟨i, -, rfl⟩ := List.mem_map.mp hmem
  simpa using Interaction.toAccess_kind_ne_exit i

end SP1Clean.Extracted
