import SP1CleanTest.Alignment.Audit.BranchCompilerRoundTrip
import SP1Clean.Soundness.HostFinalMemory
import ToClean.Air.EnsembleBuild
import ToClean.Air.FiniteLookup
import ToClean.Air.ChannelRegistry

/-! # Compiler-derived branch witness for the complete local host assembly

The only instruction input and hint are extracted from `BranchCompilerRoundTrip.compiled`.
Boundary records and preprocessing rows are derived from its actual physical interactions.
-/

namespace SP1Clean.Audit.BranchEnsemble

open Circuit Air.Flat SP1Clean.Model.Core SP1Clean.Soundness SP1Clean.TraceGen SP1Clean.Semantics

/-- The native SP1 field. -/
abbrev Fp := ZMod SP1Prime
/-- The previously checked semantic branch/compiler fixture. -/
abbrev image := BranchCompilerRoundTrip.image
/-- Canonical finite source snapshot for the same official Sail state. -/
def source : ExecutionSnapshot where
  sail := { registers := (Target.configuredState 65536).regs, memory := image.initialMemory }
  host := {}
  clock := 1
/-- Branches preserve the complete register and RAM snapshot. -/
def target : MemorySnapshot := source.sail.memorySnapshot
/-- The actual complete local host assembly, including target validators and change demand. -/
def assembly (target : MemorySnapshot) :=
  HostFinalMemory.ensemble (p := SP1Prime) image source target
    (HostHintQueueBoundary.initial []) source.host HostCallReceivers.available
    (HostHintReadLocal.sourceResources []) [] (HostFinalMemory.source_unique_names image source target)
/-- Public ordinary-step endpoints, not a HALT endpoint claim. -/
def header : SP1PublicIO Fp where
  init_clk_0_16 := 1
  init_clk_16_24 := 0
  init_clk_24_32 := 0
  init_clk_32_48 := 0
  init_pc0 := 0
  init_pc1 := 1
  init_pc2 := 0
  final_clk_0_16 := 9
  final_clk_16_24 := 0
  final_clk_24_32 := 0
  final_clk_32_48 := 0
  final_pc0 := 4092
  final_pc1 := 1
  final_pc2 := 0
  exit_code := 0
  is_execution_shard := 1
  committed_value_digest := Vector.replicate 32 0
/-- Empty generation input; semantic data is derived from the committed physical rows. -/
def data : ProverData Fp := BranchCompilerRoundTrip.data
/-- An input seed retains the actual component position and witness hint. -/
structure Seed where
  table : ℕ
  cells : List Fp
  hint : ProverHint Fp := ProverHint.empty Fp
/-- A provider seed needs no external hint. -/
def Seed.ofCells (table : ℕ) (cells : List Fp) : Seed := ⟨table, cells, ProverHint.empty Fp⟩
/-- Evaluate a field word from a natural boundary key. -/
def word (value : ℕ) : Word Fp := Target.bitVecToWord (BitVec.ofNat 64 value)
/-- Decode a seed at its component's exact input shape; the finite fixture checks every length. -/
def Seed.input (seed : Seed) (component : Component Fp) : component.Input Fp :=
  fromElements (Vector.ofFn fun index => seed.cells[index.val]?.getD 0)
/-- The sole active instruction uses the actual compiler payload and hint. -/
def branchSeed : Seed :=
  ⟨18, (toElements (BranchCompilerRoundTrip.event.toBranchInputs (p := SP1Prime))).toList,
    BranchCompilerRoundTrip.event.toBranchHint⟩
/-- A physical row generated by the actual selected component. -/
def Seed.build (seed : Seed) (component : Component Fp) : Array Fp :=
  component.buildRow (seed.input component) data seed.hint
/-- Concrete interaction messages, including zero multiplicities, named for the authenticated export inventory. -/
abbrev Ledger := List (String × List Fp × Fp)
/-- Extract actual row operations without replacing their expression evaluation. -/
def rowLedger (component : Component Fp) (row : Array Fp) : Ledger :=
  let env := Environment.fromArray row data
  component.rowOperations.interactions.map fun interaction =>
    (interaction.channel.name, (interaction.msg.map env).toList, env interaction.mult)
/-- Actual compiler-built branch interactions; all providers are derived from this ledger. -/
def branchLedger : Ledger := rowLedger BranchChip.component BranchCompilerRoundTrip.row
/-- Decode Memory records of the requested polarity from the instruction's actual ledger. -/
def memoryDemand (positive : Bool) : List (Channels.MemoryMsg Fp) :=
  (branchLedger.filter fun entry => entry.1 == "SP1Memory" &&
    entry.2.2 == (if positive then 1 else -1)).map fun entry =>
      fromElements (Vector.ofFn fun index => entry.2.1[index.val]?.getD 0)
/-- Canonical address order supplies ordered boundary links without duplicate authentication. -/
def orderedMemory (positive : Bool) : List (Channels.MemoryMsg Fp) :=
  (memoryDemand positive).mergeSort (fun a b => a.addr0.val ≤ b.addr0.val)
/-- Source authentication records follow the actual initial register pulls. -/
def sourceSeeds : List Seed :=
  ((orderedMemory false).foldl (fun (acc : ℕ × List Seed) record =>
    let address := record.addr0.val
    let input := OrderedSnapshotProvider.populate
      (SnapshotRegisterProvider.populate source.sail.memorySnapshot (BitVec.ofNat 5 address))
      acc.1 address
    (address + 1, acc.2 ++ [Seed.ofCells 0 (toElements input).toList])) (0, [])).2
/-- Complete final records follow the actual latest register pushes. -/
def finalSeeds : List Seed :=
  ((orderedMemory true).foldl (fun (acc : ℕ × List Seed) record =>
    let address := record.addr0.val
    let input := OrderedMemoryProvider.populate record acc.1 address
    (address + 1, acc.2 ++ [Seed.ofCells 3 (toElements input).toList])) (0, [])).2
/-- Every published final receipt is checked against the fixed complete target snapshot. -/
def validatorSeeds : List Seed :=
  (orderedMemory true).map fun record =>
    Seed.ofCells 87 (toElements (⟨record, 0⟩ : FinalRegisterCheck.Inputs Fp)).toList
/-- Terminate the actual finite ordered register inventory. -/
def terminal (table : ℕ) (records : List (Channels.MemoryMsg Fp)) : Seed :=
  let previous := records.foldl (fun _ record => record.addr0.val + 1) 0
  Seed.ofCells table (toElements (OrderedBoundaryEnd.populate (word previous)
    (OrderedMemoryEnsemble.endKey (p := SP1Prime)))).toList
/-- Program provider inputs are the exact demanded instruction messages. -/
def programSeeds : List Seed :=
  (branchLedger.filter fun entry => entry.1 == "SP1Program" && entry.2.2 != 0).map fun entry =>
    let message : Channels.ProgramMsg Fp :=
      fromElements (Vector.ofFn fun index => entry.2.1[index.val]?.getD 0)
    Seed.ofCells 6 (toElements (DecodedProgramProvider.inputOfMessage message (-entry.2.2))).toList
/-- Unchanged host-bank endpoints, physically present even though this step makes no host call. -/
def hostTerminals : List Seed :=
  [85, 86].map fun index =>
    Seed.ofCells index (toElements (HostCommitBoundary.initial (p := SP1Prime))).toList
/-- All non-Byte rows use the compiler and its demanded authentication inventory. -/
def consumerSeeds : List Seed :=
  [branchSeed] ++ sourceSeeds ++ finalSeeds ++ validatorSeeds ++ programSeeds ++
    [terminal 2 (orderedMemory false), terminal 5 (orderedMemory true)] ++ hostTerminals ++
    [Seed.ofCells 57 (List.replicate (size HaltChip.Inputs) 0)]
/-- Every seed must name an installed table and provide exactly its declared input width. -/
def seedValid (target : MemorySnapshot) (seed : Seed) : Bool :=
  match (assembly target).tables[seed.table]? with
  | none => false
  | some component => seed.cells.length == component.rowOffset
/-- Evaluate one seed, failing closed if its component position is absent. -/
def seedLedger? (target : MemorySnapshot) (seed : Seed) : Option Ledger :=
  match (assembly target).tables[seed.table]? with
  | none => none
  | some component => if seed.cells.length != component.rowOffset then none else
      some (rowLedger component (seed.build component))
/-- Demand one actual Byte or Range provider row, rejecting unsupported message shapes. -/
def byteSeed? (entry : String × List Fp × Fp) : Option (Option Seed) :=
  if entry.1 != "SP1Byte" || entry.2.2 == 0 then some none else
  match entry.2.1 with
  | [opcode, a, b, c] =>
    if opcode == 3 then some (some (Seed.ofCells 32 [b, c, -entry.2.2]))
    else if opcode == 4 then some (some (Seed.ofCells 37 [b, c, -entry.2.2]))
    else if opcode == 5 then some (some (Seed.ofCells 33 [b, -entry.2.2]))
    else if opcode == 6 && b.val < 17 then some (some (Seed.ofCells (38 + b.val) [a, -entry.2.2]))
    else none
  | _ => none
/-- Extend all physical consumer demand, including the public verifier, with real providers. -/
def seeds? (target : MemorySnapshot) (input : SP1PublicIO Fp) (consumers : List Seed) :
    Option (List Seed) := do
  let ledgers ← consumers.mapM (seedLedger? target)
  let verifier := (assembly target).verifierOperations.interactionValues
    (Environment.fromInput input data) |>.map fun interaction =>
      (interaction.channel.name, interaction.msg.toList, interaction.mult)
  let providers ← (verifier ++ ledgers.flatten).mapM byteSeed?
  let generated := providers.filterMap id
  if generated.all (seedValid target) then some (consumers ++ generated) else none
private theorem noFixed (target : MemorySnapshot) (component : Component Fp)
    (member : component ∈ (assembly target).tables) : component.fixedColumns = none := by
  have all : (assembly target).tables.all (fun component => component.fixedColumns.isNone) = true := by rfl
  exact Option.isNone_iff_eq_none.mp (List.all_eq_true.mp all component member)

/-- Every table remains installed; unused instruction and host tables have zero physical rows. -/
def builtTables (target : MemorySnapshot) (seeds : List Seed) : List (Table Fp) :=
  let components := (assembly target).tables
  List.ofFn fun index : Fin components.length =>
    let component := components[index]
    Table.buildHinted component ((seeds.filter fun seed => seed.table == index.val).map fun seed =>
      (seed.input component, seed.hint)) data
      (by simp only [Component.fixedRowsMatch, noFixed target component (List.getElem_mem _)])
/-- All built tables retain the assembly's original component identities and order. -/
theorem builtTables_components (target : MemorySnapshot) (seeds : List Seed) :
    (builtTables target seeds).map (·.component) = (assembly target).tables := by
  simp only [builtTables, List.map_ofFn]
  exact List.ofFn_getElem
/-- Building rows never changes the fixed 89-table host inventory. -/
theorem builtTables_length (target : MemorySnapshot) (seeds : List Seed) :
    (builtTables target seeds).length = 89 := by
  simp only [builtTables, List.length_ofFn]
  rfl
/-- The exact raw Clean witness on the original, unmodified host assembly. -/
def witness (target : MemorySnapshot) (input : SP1PublicIO Fp) (seeds : List Seed) :
    EnsembleWitness (assembly target) :=
  EnsembleWitness.ofTables _ (builtTables target seeds) input (builtTables_components target seeds)

/-- The finite source is exactly the source of the official Sail/compiler regression. -/
theorem source_realizes : source.realize = ⟨BranchCompilerRoundTrip.source, {}, 1⟩ := rfl

/-- Source providers are bound to all registers and every native-address memory byte. -/
theorem source_memory_realizes : source.sail.memorySnapshot.Realizes BranchCompilerRoundTrip.source := by
  exact source.sail.memorySnapshot_realizes (Target.cfgState_init 65536)

/-- The complete target snapshot realizes the same normally retiring official Sail target. -/
theorem target_realizes : target.Realizes BranchCompilerRoundTrip.target := by
  constructor
  · intro index
    have unchanged := BranchCompilerRoundTrip.target_effect.regs
    change ∀ index, BranchCompilerRoundTrip.target.get_reg? index =
      BranchCompilerRoundTrip.source.get_reg? index at unchanged
    exact (unchanged index).trans (source_memory_realizes.1 index)
  · intro address bound
    exact (BranchCompilerRoundTrip.target_effect.mem.1 rfl address).trans
      (source_memory_realizes.2 address bound)

/-- The physical branch seed preserves the exact input and compiler hint of the earlier local row. -/
theorem branchSeed_build : branchSeed.build BranchChip.component = BranchCompilerRoundTrip.row := by
  have input : branchSeed.input BranchChip.component =
      BranchCompilerRoundTrip.event.toBranchInputs (p := SP1Prime) := by
    unfold Seed.input branchSeed
    conv_rhs => rw [← ProvableType.fromElements_toElements
      (BranchCompilerRoundTrip.event.toBranchInputs (p := SP1Prime))]
    congr 1
    ext index bound
    simp only [Vector.getElem_ofFn, Vector.getElem?_toList]
    have bound' : index < size BranchChip.Inputs := bound
    rw [Vector.getElem?_eq_getElem bound']
    rfl
  unfold Seed.build
  rw [input]
  rfl

end SP1Clean.Audit.BranchEnsemble
