import SP1Clean.Native.Operations.HintQueueBoundary
import SP1Clean.Soundness.HostHintReadLocalQueue

/-! # Installing the queue boundary in the local verifier

The real witness retains every physical instruction, handler, and resource table. Its verifier
runs the queue boundary exactly once. A derived singleton representation preserves all constraints
and the full interaction ledger, so existing installed execution proofs continue to apply.
The final cursor is an instance parameter; outgoing snapshot agreement and dynamic allocation
history are not conclusions of this boundary construction.
-/

namespace SP1Clean.Soundness.HostHintQueueBoundary

open Circuit Air.Flat Model.Core HostHintQueue HostHintReadLocal

variable {p : ℕ} [Fact p.Prime] [Fact (2 ^ 25 < p)]

local instance : Fact (2 ^ 17 < p) := ⟨by have := Fact.out (p := 2 ^ 25 < p); omega⟩

abbrev boundary (source : ExecutionSnapshot) (final : State (ZMod p)) :=
  SP1Clean.HostHintQueueBoundary.closed source.host.io.hints final

def ensemble (image : ProgramImage) (source : ExecutionSnapshot) (final : State (ZMod p))
    (others : List (HostLocalHandoff.Receiver (p := p))) (resources : List (Component (ZMod p)))
    (channels : List (RawChannel (ZMod p))) : Ensemble (ZMod p) SP1PublicIO :=
  (boundary source final).install (HostHintReadLocal.ensemble image source others resources channels)

variable {image : ProgramImage} {source : ExecutionSnapshot} {final : State (ZMod p)}
  {others : List (HostLocalHandoff.Receiver (p := p))} {resources : List (Component (ZMod p))}
  {channels : List (RawChannel (ZMod p))}

/-- Table representation for the existing proofs; the appended row is generated by the verifier. -/
def expanded (witness : EnsembleWitness (ensemble image source final others resources channels)) :
    EnsembleWitness (HostHintReadLocal.ensemble image source others
      (resources ++ [⟨(boundary source final).circuit⟩]) channels) :=
  EnsembleWitness.ofTables _ ((boundary source final).expand witness).tables witness.data witness.publicInput
    (by
      rw [EnsembleWitness.tables_map_component]
      simp only [ClosedVerifier.asTable, HostHintReadLocal.ensemble, HostLocalHandoff.ensemble,
        HostLocalCore.ensemble, HostLocalCore.tables, List.append_assoc])
    ((boundary source final).expand witness).same_data

theorem expanded_allTables (witness : EnsembleWitness (ensemble image source final others resources channels)) :
    (expanded witness).allTables = ((boundary source final).expand witness).allTables := rfl

theorem expanded_constraints (witness : EnsembleWitness (ensemble image source final others resources channels))
    (constraints : witness.Constraints) : (expanded witness).Constraints := by
  rw [EnsembleWitness.Constraints, expanded_allTables]
  exact (boundary source final).expand_constraints witness constraints

/-- Exact transport retains Memory and every other channel, including their count bounds. -/
theorem expanded_interactions (witness : EnsembleWitness (ensemble image source final others resources channels))
    (channel : RawChannel (ZMod p)) :
    ((expanded witness).interactionsWith channel).Perm (witness.interactionsWith channel) :=
  (boundary source final).expand_interactions witness channel

theorem expanded_balanced (witness : EnsembleWitness (ensemble image source final others resources channels))
    (balanced : witness.BalancedChannels) : (expanded witness).BalancedChannels := by
  intro channel member
  apply balancedInteractions_of_perm (balanced channel ?_) (expanded_interactions witness channel).symm
  simp only [ensemble, ClosedVerifier.install, HostHintReadLocal.ensemble, HostLocalHandoff.ensemble,
    HostLocalCore.ensemble, List.flatMap_append, List.flatMap_cons, List.flatMap_nil,
    List.append_nil, List.mem_cons, List.mem_append] at member ⊢
  tauto

theorem source_binding (witness : EnsembleWitness (ensemble image source final others resources channels))
    (constraints : witness.Constraints) :
    (SP1Clean.HostHintQueueBoundary.initial (p := p) source.host.io.hints).Binds
      (HintQueue.ofList source.host.io.hints).1 source.host.io.hints := by
  apply SP1Clean.HostHintQueueBoundary.initial_binds
  have checked := ((boundary source final).verifier_constraints _ witness.publicInput witness.data).mp
    (EnsembleWitness.verifierConstraints_of_constraints constraints)
  have raw := ((boundary source final).singleton_constraints witness.data).mp checked.2
  change ((SP1Clean.HostHintQueueBoundary.main source.host.io.hints final ()).operations 0).ConstraintsHold _ at raw
  simpa only [SP1Clean.HostHintQueueBoundary.main, circuit_norm, ite_eq_left_iff,
    one_ne_zero, imp_false, not_not] using raw

omit [Fact (2 ^ 25 < p)] in
/-- The boundary uses only queue state, and cannot supply any record or CPU/word-cursor edge. -/
theorem boundary_silent (channel : RawChannel (ZMod p)) (different : channel ≠ stateChannel.toRaw) :
    channel ∉ (boundary source final).circuit.channels := by
  change channel ∉ [stateChannel.toRaw, stateChannel.toRaw]
  simpa only [List.mem_cons, List.not_mem_nil, or_false, or_self] using different

omit [Fact (2 ^ 25 < p)] in
theorem expanded_interface (interface : ExtensionInterface others resources) :
    ExtensionInterface others (resources ++ [⟨(boundary source final).circuit⟩]) := by
  have split (component : Component (ZMod p))
      (member : component ∈ others.map (·.component) ++ (resources ++ [⟨(boundary source final).circuit⟩])) :
      component ∈ others.map (·.component) ++ resources ∨ component = ⟨(boundary source final).circuit⟩ := by
    simpa only [List.mem_append, List.mem_singleton, or_assoc] using member
  have byte : Channels.byteChannel.toRaw ∉ (boundary source final).circuit.channels :=
    boundary_silent _ (by simp [Channels.byteChannel, stateChannel, Channel.toRaw])
  constructor
  · constructor
    · intro component member env checked
      rcases split component member with old | rfl
      · exact interface.chronology.byte component old env checked
      · apply Operations.requirements_of_not_mem _ _ _
          (Component.inChannelsOrRequirements_of_constraints env checked)
        exact fun used => byte (List.mem_append_right _ used)
    · intro component member
      rcases split component member with old | rfl
      · exact interface.chronology.state component old
      · exact boundary_silent _ (by simp [Channels.stateChannel, stateChannel, Channel.toRaw])
  · intro component member
    rcases List.mem_append.mp member with old | added
    · exact interface.hostCall component old
    · obtain rfl := List.mem_singleton.mp added
      exact boundary_silent _ (by simp [HostCallChip.channel, stateChannel, Channel.toRaw])
  · intro component member
    rcases split component member with old | rfl
    · exact interface.cursor component old
    · exact boundary_silent _ (by simp [HintReadWordChip.stateChannel, stateChannel, Channel.toRaw])

theorem extraTables_eq
    (witness : EnsembleWitness (ensemble image source final HostCallReceivers.available resources channels)) :
    extraTables (expanded witness) = witness.tables.drop 83 ++ [(boundary source final).singleton witness.data] := by
  have bound : 83 ≤ witness.tables.length := by
    rw [← witness.same_length]
    change 83 ≤ (HostLocalCore.tables image source _).length
    rw [HostLocalCore.tables_length]
    have count : (HostCallReceivers.available (p := p)).length = 20 := rfl
    simp only [List.length_append, List.length_map, List.length_cons, count,
      HostHintReadHandoff.wordResources, List.length_nil]
    omega
  change (((witness.tables ++ [(boundary source final).singleton witness.data]).drop 60).drop 21).drop 2 = _
  rw [List.drop_drop, List.drop_drop, List.drop_append_of_le_length bound]

/-- The full installed resource ledger supplies the two endpoints without a witness-side equation. -/
theorem endpoints
    (witness : EnsembleWitness (ensemble image source final HostCallReceivers.available resources channels))
    (silent : ∀ component ∈ resources, stateChannel.toRaw ∉ component.circuit.channels) :
    (extraTables (expanded witness)).flatMap (·.interactionsWith stateChannel.toRaw) =
      [stateChannel.pushedValue (SP1Clean.HostHintQueueBoundary.initial source.host.io.hints),
       stateChannel.pulledValue final] := by
  have components := extraTables_components (expanded witness)
  rw [extraTables_eq, List.map_append, List.map_cons, List.map_nil] at components
  have mapped : (witness.tables.drop 83).map (·.component) = resources :=
    List.append_cancel_right components
  have empty : (witness.tables.drop 83).flatMap (·.interactionsWith stateChannel.toRaw) = [] := by
    apply List.flatMap_eq_nil_iff.mpr
    intro table member
    apply Table.interactionsWith_nil_of_channel_not_mem
    apply silent table.component
    rw [← mapped]
    exact List.mem_map_of_mem (f := fun table : Table (ZMod p) => table.component) member
  rw [extraTables_eq, List.flatMap_append, empty, List.nil_append, List.flatMap_cons,
    List.flatMap_nil, List.append_nil, ClosedVerifier.singleton_interactions]
  exact SP1Clean.HostHintQueueBoundary.values ..

/-- Every actual queue-handler row lies on the uniquely anchored path. Record authentication
is retained for dynamic providers; this version covers resources without additional queue edges. -/
theorem queue_ordered
    (witness : EnsembleWitness (ensemble image source final HostCallReceivers.available resources channels))
    (interface : ExtensionInterface HostCallReceivers.available resources)
    (store : HintQueue.Store) (authenticated : RecordAuthentication (expanded witness) store)
    (silent : ∀ component ∈ resources, stateChannel.toRaw ∉ component.circuit.channels)
    (constraints : witness.Constraints) (balanced : witness.BalancedChannels) :
    ∃ path : List (HostQueueOrder.Row (p := p)),
      path.Perm (TransitionView.readIndexedRows HostQueueOrder.indices (queueTables (expanded witness))) ∧
      Walk.IsWalk HostQueueOrder.edge (SP1Clean.HostHintQueueBoundary.initial source.host.io.hints) final path :=
  queue_ordered_of_endpoints (expanded witness) (expanded_interface interface) store authenticated
    (expanded_constraints witness constraints) (expanded_balanced witness balanced) _ _ (endpoints witness silent)

/-- The fixed providers and the derived boundary authenticate all actual immutable-record sources. -/
theorem source_authentication
    (witness : EnsembleWitness (ensemble image source final HostCallReceivers.available
      (sourceResources source.host.io.hints) channels))
    (constraints : witness.Constraints) :
    RecordAuthentication (expanded witness) (HintQueue.ofList source.host.io.hints).1 := by
  apply record_authentication_of_components (expanded witness) _ _ (expanded_constraints witness constraints)
  intro component member
  have split : component ∈ (HostCallReceivers.available (p := p)).map (·.component) ++
      sourceResources source.host.io.hints ∨ component = ⟨(boundary source final).circuit⟩ := by
    simpa only [List.mem_append, List.mem_singleton, or_assoc] using member
  rcases split with old | rfl
  · exact source_record_sources source.host.io.hints _ (.refl _) component old
  · constructor <;> apply Component.Authenticates.of_silent
    · exact boundary_silent _ (by simp [nodeChannel, stateChannel, Channel.toRaw])
    · exact boundary_silent _ (by simp [wordChannel, stateChannel, Channel.toRaw])

/-- The implemented source/HINT_LEN/HINT_READ registration needs no record-authentication or
endpoint premise from its caller. This is a token-path theorem, not yet semantic head history. -/
theorem source_queue_ordered
    (witness : EnsembleWitness (ensemble image source final HostCallReceivers.available
      (sourceResources source.host.io.hints) channels))
    (constraints : witness.Constraints) (balanced : witness.BalancedChannels) :
    ∃ path : List (HostQueueOrder.Row (p := p)),
      path.Perm (TransitionView.readIndexedRows HostQueueOrder.indices (queueTables (expanded witness))) ∧
      Walk.IsWalk HostQueueOrder.edge (SP1Clean.HostHintQueueBoundary.initial source.host.io.hints) final path := by
  apply queue_ordered witness (source_interface source.host.io.hints) (HintQueue.ofList source.host.io.hints).1
    _ _ constraints balanced
  · exact source_authentication witness constraints
  · intro component member used
    have present := List.contains_iff_mem.mpr (List.mem_map_of_mem (f := RawChannel.name) used)
    simp only [sourceResources, List.mem_cons, List.not_mem_nil, or_false] at member
    rcases member with rfl | rfl <;> change false = true at present <;> contradiction

end SP1Clean.Soundness.HostHintQueueBoundary
